export const carteOptions = [
  {
    name: "Dedicated email blast",
    value: 995,
  },
  {
    name: "Sponsored blog post",
    value: 995,
  },
  {
    name: "Reception table",
    value: 1200,
  },
  {
    name: "Power",
    value: 75,
  },
  {
    name: "Internet",
    value: 25,
  },
  {
    name: "Social posts",
    value: 495,
  },
  {
    name: "Swag bag inclusion/Distribution table",
    value: 495,
  },
];

export const categories: string[] = [
  "Bar Services",
  "Beauty Services",
  "Bridal Salons",
  "Catering",
  "Dance Lessons",
  "Decor",
  "Destination Weddings & Honeymoons",
  "DJs",
  "Event Production",
  "Favors & Gifts",
  "Finance & Legal",
  "Florists",
  "Hotels",
  "Invitations",
  "Jewelers",
  "Menswear",
  "Music & Entertainment",
  "Officiants",
  "Photo Booths",
  "Planners",
  "Press",
  "Public Relations",
  "Real Estate",
  "Reception Venues",
  "Registry & Services",
  "Rehearsal Dinners, Bridal Showers",
  "Tourism Boards",
  "Transportation",
  "Travel Specialists & Insurance",
  "Videographers",
  "Wedding Bands",
  "Wedding Cakes",
  "Wedding Photographers",
  "Wedding Rentals",
  "Wellness & Spa",
];
